USE june_07;
CREATE TABLE water_tank(S_N int,brand varchar(50),location varchar(50),height bigint,weight bigint,capacity varchar(40),manufactured_date
varchar(30),expiry_date varchar(50));
  INSERT INTO water_tank VALUES(1, 'Reliance', 'btm', 100, 200, '50 gallons', '2020-01-01', '2025-01-01');
  INSERT INTO water_tank VALUES(2, 'Supreme', 'rajajinagar', 120, 250, '75 gallons', '2019-05-15', '2024-05-15');
  INSERT INTO water_tank VALUES(3, 'Astral', 'electronic_city', 150, 300, '100 gallons', '2021-03-10', '2026-03-10');
  INSERT INTO water_tank VALUES(4, 'Finolex', 'marathalli', 110, 180, '40 gallons', '2020-04-20', '2025-04-20');
  INSERT INTO water_tank VALUES(5, 'Jain', 'hebbal', 130, 220, '60 gallons', '2019-09-05', '2024-09-05');
  INSERT INTO water_tank VALUES(6, 'Prince', 'yallahanka', 140, 260, '80 gallons', '2020-11-30', '2025-11-30');
  INSERT INTO water_tank VALUES(7, 'Kisan', 'banshankari', 160, 280, '90 gallons', '2019-12-25', '2024-12-25');
  INSERT INTO water_tank VALUES(8, 'Dutron', 'chikballapur', 115, 190, '45 gallons', '2021-02-14', '2026-02-14');
  INSERT INTO water_tank VALUES(9, 'Texmo', 'chikmangalur', 125, 210, '55 gallons', '2020-03-05', '2025-03-05');
  INSERT INTO water_tank VALUES(10, 'Captian', 'chandapura', 135, 240, '70 gallons', '2022-04-17', '2027-04-17');
  INSERT INTO water_tank VALUES(11, 'Sudhakar', 'ameerpet', 105, 180, '40 gallons', '2020-06-20', '2025-06-20');
  INSERT INTO water_tank VALUES(12, 'Ajay', 'Gacchibouli', 115, 200, '50 gallons', '2021-09-11', '2026-09-11');
  INSERT INTO water_tank VALUES(13, 'Ori-plast', 'Ramnagar', 145, 270, '85 gallons', '2022-02-22', '2027-02-22');
  INSERT INTO water_tank VALUES(14, 'kothari', 'Siddharthpur', 155, 290, '95 gallons', '2020-04-02', '2025-04-02');
  INSERT INTO water_tank VALUES(15, 'vectus', 'Goa', 165, 310, '105 gallons', '2022-08-15', '2027-08-15');
  INSERT INTO water_tank VALUES(16, 'Jaisin', 'mysore', 120, 180, '40 gallons', '2021-12-01', '2026-12-01');
  INSERT INTO water_tank VALUES(17, 'Utkarsh', 'chile', 130, 210, '55 gallons', '2022-03-25', '2027-03-25');
  INSERT INTO water_tank VALUES(18, 'Varun', 'rajastan', 150, 240, '70 gallons', '2023-06-10', '2028-06-10');
  INSERT INTO water_tank VALUES(19, 'Nelima', 'punjab', 110, 170, '35 gallons', '2021-02-14', '2026-02-14');
  INSERT INTO water_tank VALUES(20, 'Naina', 'Lucknow', 140, 200, '50 gallons', '2022-05-07', '2027-05-07');
CREATE TABLE shoe_info (shoe_id int,brand VARCHAR(50),model VARCHAR(50),color VARCHAR(30),size int,gender VARCHAR(20),material VARCHAR(50),price int);
INSERT INTO shoe_info VALUES(1, 'Nike', 'Air Max 270', 'Black/White', 10, 'Men', 'Textile/Synthetic', 12999);
INSERT INTO shoe_info VALUES(2, 'Adidas', 'Ultraboost 21', 'Grey/White', 9, 'Women', 'Textile/Synthetic', 17999);
INSERT INTO shoe_info VALUES(3, 'Puma', 'RS-X3 Puzzle', 'Red/Blue/Yellow', 8, 'Unisex', 'Textile/Synthetic', 8999);
INSERT INTO shoe_info VALUES(4, 'Reebok', 'Classic Leather', 'White', 11, 'Men', 'Leather', 7999);
INSERT INTO shoe_info VALUES(5, 'Vans', 'Authentic', 'Black', 7, 'Women', 'Canvas', 4999);
INSERT INTO shoe_info VALUES(6, 'New Balance', 'Fresh Foam Arishi', 'Navy', 9, 'Men', 'Synthetic', 6999);
INSERT INTO shoe_info VALUES(7, 'Converse', 'Chuck Taylor All Star', 'White', 8, 'Unisex', 'Canvas', 5999);
INSERT INTO shoe_info VALUES(8, 'Under Armour', 'HOVR Phantom 2', 'Black/Grey', 9, 'Men', 'Textile/Synthetic', 13999);
INSERT INTO shoe_info VALUES(9, 'Skechers', 'Go Walk 5', 'Black', 8, 'Women', 'Textile/Synthetic', 5999);
INSERT INTO shoe_info VALUES(10, 'ASICS', 'Gel-Kayano 27', 'Blue/Pink', 7, 'Women', 'Mesh/Synthetic', 11999);
INSERT INTO shoe_info VALUES(11, 'Nike', 'Air Force 1', 'White', 9, 'Men', 'Leather', 8999);
INSERT INTO shoe_info VALUES(12, 'Adidas', 'Stan Smith', 'Green', 8, 'Women', 'Leather', 6999);
INSERT INTO shoe_info VALUES(13, 'Puma', 'Cali', 'White/Pink', 7, 'Women', 'Leather', 5999);
INSERT INTO shoe_info VALUES(14, 'Reebok', 'Club C 85', 'Black', 10, 'Men', 'Leather', 7999);
INSERT INTO shoe_info VALUES(15, 'Vans', 'Old Skool', 'Black/White', 9, 'Unisex', 'Canvas', 5999);
INSERT INTO shoe_info VALUES(16, 'New Balance', '997H', 'Grey/White', 10, 'Men', 'Suede/Textile', 8999);
INSERT INTO shoe_info VALUES(17, 'Converse', 'One Star', 'Navy', 8, 'Unisex', 'Suede', 6999);
INSERT INTO shoe_info VALUES(18, 'Under Armour', 'Charged Assert 8', 'Black/Red', 11, 'Men', 'Textile/Synthetic', 6999);
INSERT INTO shoe_info VALUES(19, 'Skechers', 'DLites', 'Black/White', 8, 'Women', 'Leather/Synthetic', 4999);
INSERT INTO shoe_info VALUES(20, 'ASICS', 'Gel-Nimbus 23', 'Blue/Yellow', 9, 'Men', 'Mesh/Synthetic', 13999);
CREATE TABLE mobile_info (id int,brand VARCHAR(50),model VARCHAR(50),storage VARCHAR(20),ram VARCHAR(20),display_size int,camera_resolution VARCHAR(30),price int);
INSERT INTO mobile_info VALUES(1,'Apple', 'iPhone 12', '256GB', '6GB', 6.1, '12MP + 12MP', 799);
INSERT INTO mobile_info VALUES(2,'Samsung', 'Galaxy S21', '128GB', '8GB', 6.2, '12MP + 12MP + 64MP', 999);
INSERT INTO mobile_info VALUES(3,'OnePlus', '9 Pro', '256GB', '12GB', 6.7, '48MP + 50MP + 8MP', 899);
INSERT INTO mobile_info VALUES(4,'Google', 'Pixel 5', '128GB', '8GB', 6.0, '12.2MP + 16MP', 699);
INSERT INTO mobile_info VALUES(5,'Xiaomi', 'Mi 11', '256GB', '8GB', 6.81, '108MP + 13MP + 5MP', 799);
INSERT INTO mobile_info VALUES(6,'OPPO', 'Find X3 Pro', '256GB', '12GB', 6.7, '50MP + 50MP + 13MP + 3MP', 1099);
INSERT INTO mobile_info VALUES(7,'Samsung', 'Galaxy Note 20 Ultra', '256GB', '12GB', 6.9, '108MP + 12MP + 12MP', 1299);
INSERT INTO mobile_info VALUES(8,'Apple', 'iPhone SE', '64GB', '3GB', 4.7, '12MP', 399);
INSERT INTO mobile_info VALUES(9,'Xiaomi', 'Redmi Note 10 Pro', '128GB', '6GB', 6.67, '64MP + 8MP + 5MP + 2MP', 299);
INSERT INTO mobile_info VALUES(10,'OnePlus', 'Nord CE 5G', '128GB', '6GB', 6.43, '64MP + 8MP + 2MP', 399);
INSERT INTO mobile_info VALUES(11, 'Apple', 'iPhone 11', '128GB', '4GB', 6.1, '12MP + 12MP', 64999);
INSERT INTO mobile_info VALUES(12, 'Samsung', 'Galaxy A52', '128GB', '6GB', 6.5, '64MP + 12MP + 5MP + 5MP', 27999);
INSERT INTO mobile_info VALUES(13, 'OnePlus', '8T', '128GB', '8GB', 6.55, '48MP + 16MP + 5MP + 2MP', 42999);
INSERT INTO mobile_info VALUES(14, 'Google', 'Pixel 4a', '128GB', '6GB', 5.81, '12.2MP', 34999);
INSERT INTO mobile_info VALUES(15, 'Xiaomi', 'Redmi Note 9 Pro', '128GB', '6GB', 6.67, '48MP + 8MP + 5MP + 2MP', 17999);
INSERT INTO mobile_info VALUES(16, 'OPPO', 'F19 Pro', '128GB', '8GB', 6.43, '48MP + 8MP + 2MP + 2MP', 21990);
INSERT INTO mobile_info VALUES(17, 'Samsung', 'Galaxy M51', '128GB', '6GB', 6.7, '64MP + 12MP + 5MP + 5MP', 22999);
INSERT INTO mobile_info VALUES(18, 'Realme', 'Narzo 30 Pro', '128GB', '6GB', 6.5, '48MP + 8MP + 2MP', 15999);
INSERT INTO mobile_info VALUES(19, 'Vivo', 'V21 5G', '128GB', '8GB', 6.44, '64MP + 8MP + 2MP', 29990);
INSERT INTO mobile_info VALUES(20, 'Motorola', 'Moto G40 Fusion', '128GB', '6GB', 6.8, '64MP + 8MP + 2MP', 14999);
CREATE TABLE laptop_info (S_N int,brand VARCHAR(50),model VARCHAR(50),processor VARCHAR(50),ram VARCHAR(20),storage VARCHAR(20),
display_size int,price int);
INSERT INTO laptop_info VALUES(1, 'Apple', 'MacBook Pro', 'Intel Core i7', '16GB', '512GB SSD', 13, 169999);
INSERT INTO laptop_info VALUES(2, 'Dell', 'XPS 13', 'Intel Core i5', '8GB', '256GB SSD', 13, 109999);
INSERT INTO laptop_info VALUES(3, 'HP', 'Spectre x360', 'Intel Core i7', '16GB', '1TB SSD', 13, 139999);
INSERT INTO laptop_info VALUES(4, 'Lenovo', 'ThinkPad X1 Carbon', 'Intel Core i5', '8GB', '256GB SSD', 14, 119999);
INSERT INTO laptop_info VALUES(5, 'ASUS', 'ZenBook 14', 'AMD Ryzen 7', '16GB', '512GB SSD', 14, 99999);
INSERT INTO laptop_info VALUES(6, 'Acer', 'Predator Helios 300', 'Intel Core i7', '16GB', '512GB SSD', 15, 129999);
INSERT INTO laptop_info VALUES(7, 'MSI', 'GS66 Stealth', 'Intel Core i9', '32GB', '1TB SSD', 15, 249999);
INSERT INTO laptop_info VALUES(8, 'Razer', 'Blade 15', 'Intel Core i7', '16GB', '512GB SSD', 15, 179999);
INSERT INTO laptop_info VALUES(9, 'Microsoft', 'Surface Laptop 4', 'AMD Ryzen 7', '16GB', '512GB SSD', 15, 149999);
INSERT INTO laptop_info VALUES(10, 'Huawei', 'MateBook X Pro', 'Intel Core i7', '16GB', '1TB SSD', 13, 159999);
INSERT INTO laptop_info VALUES(11, 'Lenovo', 'IdeaPad Flex 5', 'AMD Ryzen 5', '8GB', '256GB SSD', 14, 64999);
INSERT INTO laptop_info VALUES(12, 'ASUS', 'ROG Zephyrus G14', 'AMD Ryzen 9', '16GB', '1TB SSD', 14, 139999);
INSERT INTO laptop_info VALUES(13, 'Dell', 'Inspiron 15 3000', 'Intel Core i3', '4GB', '1TB HDD', 15, 39999);
INSERT INTO laptop_info VALUES(14, 'HP', 'Pavilion x360', 'Intel Core i5', '8GB', '512GB SSD', 14, 67999);
INSERT INTO laptop_info VALUES(15, 'Acer', 'Swift 3', 'AMD Ryzen 7', '8GB', '512GB SSD', 14, 59999);
INSERT INTO laptop_info VALUES(16, 'MSI', 'Modern 14', 'Intel Core i7', '16GB', '512GB SSD', 14, 84999);
INSERT INTO laptop_info VALUES(17, 'Apple', 'MacBook Air', 'Apple M1', '8GB', '256GB SSD', 13, 99999);
INSERT INTO laptop_info VALUES(18, 'Lenovo', 'Legion 5', 'AMD Ryzen 7', '16GB', '512GB SSD', 15, 109999);
INSERT INTO laptop_info VALUES(19, 'ASUS', 'VivoBook 15', 'Intel Core i5', '8GB', '512GB SSD', 15, 56999);
INSERT INTO laptop_info VALUES(20, 'HP', 'Envy x360', 'AMD Ryzen 5', '8GB', '256GB SSD', 13, 89999);

CREATE TABLE bicycle_info (id INT,Brand VARCHAR(50),Model VARCHAR(60),Type VARCHAR(70),Frame_Material VARCHAR(60),
Wheel_Size VARCHAR(20),Gear_Type VARCHAR(255),Price int);
INSERT INTO bicycle_info VALUES(1, 'Trek', 'Domane SLR', 'Road', 'Carbon', '28 inches', 'Shimano 105', 2500);
INSERT INTO bicycle_info VALUES(2, 'Giant', 'Anthem 29er', 'Mountain', 'Aluminum', '29 inches', 'SRAM NX', 1800);
INSERT INTO bicycle_info VALUES(3, 'Specialized', 'Sirrus X', 'Hybrid', 'Steel', '27.5 inches', 'Shimano Alivio', 1200);
INSERT INTO bicycle_info VALUES(4, 'Cannondale', 'SuperSix Evo', 'Road', 'Carbon', '28 inches', 'Shimano Ultegra', 3500);
INSERT INTO bicycle_info VALUES(5, 'Santa Cruz', 'Tallboy', 'Mountain', 'Carbon', '27.5 inches', 'SRAM GX', 4000);
INSERT INTO bicycle_info VALUES(6, 'Electra', 'Townie', 'Cruiser', 'Steel', '26 inches', 'Single Speed', 600);
INSERT INTO bicycle_info VALUES(7, 'BMC', 'Teammachine', 'Road', 'Carbon', '28 inches', 'Shimano Dura-Ace', 6000);
INSERT INTO bicycle_info VALUES(8, 'Scott', 'Spark RC', 'Mountain', 'Carbon', '29 inches', 'SRAM XX1', 5500);
INSERT INTO bicycle_info VALUES(9, 'Cervelo', 'S5', 'Road', 'Carbon', '28 inches', 'Shimano Ultegra Di2', 5500);
INSERT INTO bicycle_info VALUES(10, 'Canyon', 'Grail', 'Gravel', 'Carbon', '700C', 'SRAM Force eTap AXS', 3000);
INSERT INTO bicycle_info VALUES(11, 'Cannondale', 'Synapse Carbon', 'Road', 'Carbon', '28 inches', 'Shimano Ultegra', 4000);
INSERT INTO bicycle_info VALUES(12, 'Trek', 'Procaliber 9.8', 'Mountain', 'Carbon', '29 inches', 'SRAM X01', 4500);
INSERT INTO bicycle_info VALUES(13, 'Giant', 'Escape 3', 'Hybrid', 'Aluminum', '700C', 'Shimano Tourney', 500);
INSERT INTO bicycle_info VALUES(14, 'Specialized', 'Stumpjumper', 'Mountain', 'Carbon', '27.5 inches', 'SRAM XX1 Eagle', 6000);
INSERT INTO bicycle_info VALUES(15, 'Canyon', 'Endurace CF SL', 'Road', 'Carbon', '28 inches', 'Shimano 105', 2500);
INSERT INTO bicycle_info VALUES(16, 'Scott', 'Genius', 'Mountain', 'Carbon', '29 inches', 'SRAM GX Eagle', 3500);
INSERT INTO bicycle_info VALUES(17, 'Cervelo', 'R3', 'Road', 'Carbon', '28 inches', 'Shimano Ultegra Di2', 5500);
INSERT INTO bicycle_info VALUES(18, 'Giant', 'Trance X', 'Mountain', 'Aluminum', '29 inches', 'Shimano Deore', 3000);
INSERT INTO bicycle_info VALUES(19, 'Trek', 'FX 2 Disc', 'Hybrid', 'Aluminum', '700C', 'Shimano Altus', 600);
INSERT INTO bicycle_info VALUES(20, 'Specialized', 'Diverge', 'Gravel', 'Carbon', '700C', 'SRAM Force eTap AXS', 4000);
CREATE TABLE watch_info (id int,watch_model VARCHAR(50),brand VARCHAR(50),case_material VARCHAR(50),strap_material VARCHAR(50),
    price int,water_resistance boolean,dial_color VARCHAR(50));
INSERT INTO watch_info VALUES(1, 'Rolex Submariner', 'Rolex', 'Stainless Steel', 'Oystersteel', 9000, true, 'Black');
INSERT INTO watch_info VALUES(2, 'Omega Speedmaster', 'Omega', 'Stainless Steel', 'Stainless Steel', 4000, true, 'Black');
INSERT INTO watch_info VALUES(3, 'TAG Heuer Carrera', 'TAG Heuer', 'Stainless Steel', 'Leather', 3500, true, 'Silver');
INSERT INTO watch_info VALUES(4, 'Seiko Prospex', 'Seiko', 'Stainless Steel', 'Silicone', 500, true, 'Blue');
INSERT INTO watch_info VALUES(5, 'Tissot T-Touch', 'Tissot', 'Titanium', 'Rubber', 1000, true, 'Black');
INSERT INTO watch_info VALUES(6, 'Citizen Eco-Drive', 'Citizen', 'Stainless Steel', 'Stainless Steel', 250, true, 'Silver');
INSERT INTO watch_info VALUES(7, 'Casio G-Shock', 'Casio', 'Resin', 'Resin', 100, true, 'Black');
INSERT INTO watch_info VALUES(8, 'Fossil Grant', 'Fossil', 'Stainless Steel', 'Leather', 150, false, 'Brown');
INSERT INTO watch_info VALUES(9, 'Movado Museum', 'Movado', 'Stainless Steel', 'Stainless Steel', 800, false, 'Black');
INSERT INTO watch_info VALUES(10, 'Bulova Precisionist', 'Bulova', 'Stainless Steel', 'Stainless Steel', 300, true, 'Silver');
INSERT INTO watch_info VALUES(11, 'Hamilton Khaki Field', 'Hamilton', 'Stainless Steel', 'Canvas', 500, true, 'Black');
INSERT INTO watch_info VALUES(12, 'Longines Master Collection', 'Longines', 'Stainless Steel', 'Leather', 2500, true, 'Silver');
INSERT INTO watch_info VALUES(13, 'Panerai Luminor', 'Panerai', 'Stainless Steel', 'Leather', 7000, true, 'Black');
INSERT INTO watch_info VALUES(14, 'Breitling Navitimer', 'Breitling', 'Stainless Steel', 'Stainless Steel', 6000, true, 'Blue');
INSERT INTO watch_info VALUES(15, 'IWC Pilot', 'IWC', 'Stainless Steel', 'Stainless Steel', 4500, true, 'Black');
INSERT INTO watch_info VALUES(16, 'Zenith El Primero', 'Zenith', 'Stainless Steel', 'Leather', 4000, true, 'Silver');
INSERT INTO watch_info VALUES(17, 'Oris Divers Sixty-Five', 'Oris', 'Stainless Steel', 'Rubber', 1500, true, 'Blue');
INSERT INTO watch_info VALUES(18, 'Mido Multifort', 'Mido', 'Stainless Steel', 'Stainless Steel', 800, true, 'Black');
INSERT INTO watch_info VALUES(19, 'Raymond Weil Tango', 'Raymond Weil', 'Stainless Steel', 'Stainless Steel', 1200, true, 'Silver');
INSERT INTO watch_info VALUES(20, 'Seiko Presage', 'Seiko', 'Stainless Steel', 'Leather', 350, false, 'White');
CREATE TABLE refrigerator_info (id INT,brand VARCHAR(50),model VARCHAR(50),capacity FLOAT,energy_rating VARCHAR(10),defrost_type VARCHAR(20),
    color VARCHAR(20),price INT);
INSERT INTO refrigerator_info VALUES(1, 'Samsung', 'RF28N9780SG', 28.2, 'Energy', 'Frost-Free', 'Black', 2499);
INSERT INTO refrigerator_info VALUES(2, 'LG', 'LFXS28596S', 27.7, 'Star', 'Frost-Free', 'Stainless_Steel', 2199);
INSERT INTO refrigerator_info VALUES(3, 'Whirlpool', 'WRX735SDHZ', 24.5, 'Energy', 'Frost-Free', 'Steel', 1899);
INSERT INTO refrigerator_info VALUES(4, 'GE', 'GFE26JYMFS', 25.6, 'Energy', 'Frost', 'Slate', 1899);
INSERT INTO refrigerator_info VALUES(5, 'KitchenAid', 'KRFF507HPS', 26.8, 'Energy', 'Frost', 'Stainless', 2599);
INSERT INTO refrigerator_info VALUES(6, 'Bosch', 'B36CL80ENS', 20.5, 'Star', 'Frost', 'Steel', 2599);
INSERT INTO refrigerator_info VALUES(7, 'Frigidaire', 'FGSC2335TF', 22.2, 'Star', 'Free', 'Steel', 1799);
INSERT INTO refrigerator_info VALUES(8, 'Maytag', 'MFI2570FEZ', 24.7, 'Energy', 'Free', 'Stainless', 1899);
INSERT INTO refrigerator_info VALUES(9, 'Haier', 'HRF15N3AGS', 15.0, 'Energy', 'Frost', 'Steel', 999);
INSERT INTO refrigerator_info VALUES(10, 'Kenmore', 'Elite 74043', 29.8, 'Star', 'Frost', 'Stainless', 3199);
INSERT INTO refrigerator_info VALUES(11, 'Amana', 'ASD2575BRB', 24.7, 'Rated', 'Free', 'Black', 1399);
INSERT INTO refrigerator_info VALUES(12, 'Sub-Zero', 'BI-36UFD', 23.3, 'Rated5', 'Free', 'Ready', 8999);
INSERT INTO refrigerator_info VALUES(13, 'Whirlpool', 'WRS571CIHZ', 20.6, 'Energy', 'Free', 'Steel', 1699);
INSERT INTO refrigerator_info VALUES(14, 'GE Profile', 'PFE28PYNFS', 27.9, 'Energy', 'Frost', 'Stainless', 2999);
INSERT INTO refrigerator_info VALUES(15, 'LG', 'LFXS28968S', 26.2, 'Star', 'Free', 'Steel', 2199);
INSERT INTO refrigerator_info VALUES(16, 'Samsung', 'RF23R6201SR', 22.5, 'Energy', 'Frost', 'Steel', 2099);
INSERT INTO refrigerator_info VALUES(17, 'KitchenAid', 'KRSC703HPS', 22.7, 'Star', 'Free', 'Steel', 2999);
INSERT INTO refrigerator_info VALUES(18, 'Frigidaire', 'FFSS2315TS', 22.1, 'Not', 'Frost', 'Stainless', 1099);
INSERT INTO refrigerator_info VALUES(19, 'GE', 'GNE25JSKSS', 24.8, 'Energy', 'Free', 'Steel', 1799);
INSERT INTO refrigerator_info VALUES(20, 'Whirlpool', 'WRF535SWHZ', 25.2, 'Energy', 'Frost', 'Stainless', 1699);
CREATE TABLE backpack (id INT,brand VARCHAR(50),model VARCHAR(50),capacity FLOAT,color VARCHAR(20),material VARCHAR(50),laptop_compartment BOOLEAN,
    price INT);
INSERT INTO backpack VALUES(1, 'The North Face', 'Jester', 28, 'Black', 'Nylon', true, 69);
INSERT INTO backpack VALUES(2, 'Herschel Supply Co.', 'Classic', 22, 'Grey', 'Polyester', false, 59);
INSERT INTO backpack VALUES(3, 'JanSport', 'Big Student', 34, 'Navy', 'Polyester', true, 49);
INSERT INTO backpack VALUES(4, 'Osprey', 'Daylite Plus', 20, 'Orange', 'Nylon', true, 64);
INSERT INTO backpack VALUES(5, 'Patagonia', 'Refugio', 28, 'Green', 'Recycled Polyester', true, 89);
INSERT INTO backpack VALUES(6, 'Fjällräven', 'Kånken', 16, 'Sky Blue', 'Vinylon F', false, 80);
INSERT INTO backpack VALUES(7, 'Timbuk2', 'Command', 32, 'Black', 'Nylon', true, 129);
INSERT INTO backpack VALUES(8, 'Eddie Bauer', 'Stowaway', 20, 'Red', 'Polyester', false, 39);
INSERT INTO backpack VALUES(9, 'Columbia', 'Tamolitch', 28, 'Blue', 'Polyester', true, 79);
INSERT INTO backpack VALUES(10, 'Thule', 'Paramount', 30, 'Black', 'Nylon', true, 139);
INSERT INTO backpack VALUES(11, 'Deuter', 'Speed Lite', 12, 'Green', 'Ripstop Nylon', false, 89);
INSERT INTO backpack VALUES(12, 'Gregory', 'Zulu', 55, 'Red', 'Nylon', false, 199);
INSERT INTO backpack VALUES(13, 'Under Armour', 'Hustle', 25, 'Grey', 'Polyester', true, 55);
INSERT INTO backpack VALUES(14, 'Marmot', 'Kompressor', 20, 'Yellow', 'Nylon', false, 59);
INSERT INTO backpack VALUES(15, 'Kelty', 'Redwing', 44, 'Green', 'Polyester', true, 124);
INSERT INTO backpack VALUES(16, 'Black Diamond', 'Speed', 16, 'Black', 'Nylon', false, 79);
INSERT INTO backpack VALUES(17, 'Mountainsmith', 'Mayhem', 35, 'Blue', 'Cordura Nylon', true, 149);
INSERT INTO backpack VALUES(18, 'Granite Gear', 'Crown2', 60, 'Black', 'Ripstop Nylon', false, 199);
INSERT INTO backpack VALUES(19,'teryx', 'Bora AR', 63, 'Grey', 'Nylon', true, 499);
INSERT INTO backpack VALUES(20, 'Klymit', 'Motion', 30, 'Orange', 'Polyester', false, 89);

CREATE TABLE waterbottle_info (id INT,brand VARCHAR(50),model VARCHAR(50),capacity FLOAT,material VARCHAR(50),color VARCHAR(20),insulation BOOLEAN,
    price INT);
INSERT INTO waterbottle_info VALUES(1, 'Hydro Flask', 'Wide Mouth', 32, 'Stainless Steel', 'Black', true, 39);
INSERT INTO waterbottle_info VALUES(2, 'Yeti', 'Bottle', 18, 'Stainless Steel', 'Navy', true, 29);
INSERT INTO waterbottle_info VALUES(3, 'Nalgene', 'Narrow Mouth', 16, 'BPA-Free Plastic', 'Gray', false, 10);
INSERT INTO waterbottle_info VALUES(4, 'CamelBak', 'EDDY+', 25, 'BPA-Free Plastic', 'Coral', true, 15);
INSERT INTO waterbottle_info VALUES(5, 'Klean Kanteen', 'Classic', 20, 'Stainless Steel', 'Brushed Stainless', true, 25);
INSERT INTO waterbottle_info VALUES(6, 'S\'well', 'Bottle', 17, 'Stainless Steel', 'Teakwood', true, 35);
INSERT INTO waterbottle_info VALUES(7, 'Contigo', 'AUTOSEAL', 24, 'BPA-Free Plastic', 'Tiffany Blue', true, 20);
INSERT INTO waterbottle_info VALUES(8, 'Takeya', 'Actives', 18, 'Stainless Steel', 'Onyx', true, 28);
INSERT INTO waterbottle_info VALUES(9, 'CamelBak', 'Chute Mag', 32, 'BPA-Free Plastic', 'Lime', false, 20);
INSERT INTO waterbottle_info VALUES(10, 'Hydro Flask', 'Standard Mouth', 21, 'Stainless Steel', 'White', true, 32);
INSERT INTO waterbottle_info VALUES(11, 'Yeti', 'Rambler', 26, 'Stainless Steel', 'River Green', true, 45);
INSERT INTO waterbottle_info VALUES(12, 'Nalgene', 'Wide Mouth', 48, 'BPA-Free Plastic', 'Purple', false, 15);
INSERT INTO waterbottle_info VALUES(13, 'Klean Kanteen', 'Insulated', 12, 'Stainless Steel', 'Shale Black', true, 22);
INSERT INTO waterbottle_info VALUES(14, 'S\'well', 'Traveler', 16, 'Stainless Steel', 'Moonstone', true, 30);
INSERT INTO waterbottle_info VALUES(15, 'Contigo', 'Purity Glass', 20, 'Glass', 'Sangria', false, 25);
INSERT INTO waterbottle_info VALUES(16, 'CamelBak', 'Forge', 16, 'Stainless Steel', 'Olive', true, 25);
INSERT INTO waterbottle_info VALUES(17, 'Hydro Flask', 'Coffee Flask', 12, 'Stainless Steel', 'Pacific', true, 28);
INSERT INTO waterbottle_info VALUES(18, 'Takeya', 'Stainless Steel', 24, 'Stainless Steel', 'Arctic', true, 26);
INSERT INTO waterbottle_info VALUES(19, 'Yeti', 'Rambler Jr.', 12, 'Stainless Steel', 'Coral', true, 29);
INSERT INTO waterbottle_info VALUES(20, 'Nalgene', 'OTF', 24, 'BPA-Free Plastic', 'Clementine', true, 13);

CREATE TABLE remote_info (id INT,brand VARCHAR(50),model VARCHAR(50),device_type VARCHAR(50),compatibility VARCHAR(100),color VARCHAR(20),
    connectivity VARCHAR(50),price INT);
INSERT INTO remote_info VALUES(1,'Logitech','Harmony Elite','Universal_Remote','270,000 devices', 'Black','Bluetooth',299);
INSERT INTO remote_info VALUES(2, 'Samsung', 'One Remote Control', 'Smart TV Remote', '54000 devices', 'Black', 'Bluetooth', 59);
INSERT INTO remote_info VALUES(3, 'Sony', 'RMVLZ620', 'Universal Remote', 'video devices', 'Silver', 'IR', 19);
INSERT INTO remote_info VALUES(4, 'Bose', 'SoundTouch', 'Sound System Remote', 'SoundTouch devices', 'White','white',34);
INSERT INTO remote_info VALUES(5, 'Apple', 'Siri Remote', 'Apple TV Remote', 'Apple TV HD', 'Black', 'Bluetooth', 59);
INSERT INTO remote_info VALUES(6, 'Amazon', 'Fire TV Remote', 'Streaming Device Remote', 'Fire TV Cube', 'Black', 'Bluetooth', 29);
INSERT INTO remote_info VALUES(8, 'Roku', 'Voice Remote Pro', 'Streaming Device Remote', 'Roku TVs', 'Black','Bluetooth', 29);
INSERT INTO remote_info VALUES(9, 'Xfinity', 'XR15', 'Remote', 'boxes', 'Black', 'RF', 15);
INSERT INTO remote_info VALUES(10, 'Vizio', 'XRT136', 'Smart TV Remote', 'Smart TVs', 'Silver', 'IR', 12);
INSERT INTO remote_info VALUES(11, 'Philips', 'SRP3014', 'Universal Remote', 'audio/video devices', 'Black', 'IR', 17);
INSERT INTO remote_info VALUES(12, 'Sharp', 'GJ221', 'Remote', 'Smart TVs', 'Black', 'IR', 9);
INSERT INTO remote_info VALUES(13, 'TCL', 'RC280', 'Remote', 'TCL Roku TVs', 'Black', 'IR', 10);
INSERT INTO remote_info VALUES(14, 'Hisense', 'EN3V39H', 'Compatible with Hisense Smart TVs','wifi','Black', 'IR', 13);
INSERT INTO remote_info VALUES(15, 'Panasonic', 'N2QAYB000486', 'TV Remote', 'Compatible with Panasonic TVs', 'Silver', 'IR', 16);
INSERT INTO remote_info VALUES(16, 'Dish Network', '52.0', 'Satellite Receiver Remote', 'receivers', 'Black', 'IR', 25);
INSERT INTO remote_info VALUES(17, 'Sanyo', 'FXVR', 'TV Remote', 'Compatible with Sanyo TVs', 'Black', 'IR', 11);
INSERT INTO remote_info VALUES(18, 'Insignia', 'NS-RCFNA-21', 'Edition Remote','Fire TV Edition TVs','Black', 'Bluetooth', 19);
INSERT INTO remote_info VALUES(19, 'Westinghouse', 'RMT-23', 'TV Remote', 'Compatible with Westinghouse TVs', 'Black', 'IR', 8);
INSERT INTO remote_info VALUES(20, 'Magnavox', 'NH409UD', 'TV Remote', 'Compatible with Magnavox TVs', 'Black', 'IR', 14);
SELECT * FROM water_tank;
ALTER TABLE water_tank MODIFY height INT;
ALTER TABLE water_tank ADD COLUMN Type varchar(50);
ALTER TABLE water_tank RENAME COLUMN Type TO Type_of_tank;
UPDATE water_tank SET brand='Sup' WHERE S_N =2;
SELECT * FROM water_tank WHERE location='btm';
SELECT * FROM water_tank WHERE location='hebbal' AND height=130;
SELECT * FROM water_tank WHERE location='ameerpet' OR  height=105;
SELECT *FROM water_tank WHERE S_N IN(2,7,9);
SELECT *FROM water_tank WHERE S_N NOT IN(8,10);
SELECT *FROM water_tank WHERE S_N BETWEEN 1 AND 5;
SELECT COUNT(brand) FROM water_tank;
SELECT SUM(weight) AS total_weight FROM water_tank;
SELECT AVG(weight) AS AVERAGE FROM water_tank;
SELECT MIN(height) AS MIN_HEIGHT FROM water_tank;
SELECT MAX(height) AS MAX_HEIGHT FROM water_tank;
SELECT * FROM water_tank ORDER BY height;
SELECT * FROM water_tank ORDER BY height DESC;
SELECT DISTINCT(brand) FROM water_tank;
SELECT LPAD('Astral',9,'s') FROM water_tank WHERE S_N=3;
SELECT RPAD('Jain',7,'t') FROM water_tank WHERE S_N=5;
UPDATE water_tank SET brand='   kisan   ' WHERE S_N=7;
SELECT LTRIM(brand) FROM water_tank WHERE S_N=7;
SELECT RTRIM(brand) FROM water_tank WHERE S_N=7;
SELECT COUNT(capacity),capacity FROM water_tank GROUP BY capacity;
SELECT COUNT(height),height FROM water_tank GROUP BY height HAVING height>150;
SELECT *FROM water_tank WHERE brand LIKE 'a%';
SELECT *FROM water_tank WHERE brand LIKE '%l';
SELECT *FROM water_tank WHERE brand LIKE 'a%l';
SELECT UPPER(brand) FROM water_tank WHERE S_N=3;
SELECT LOWER(brand) FROM water_tank WHERE S_N=6;
SELECT UPPER(brand) FROM water_tank;
DELETE FROM water_tank WHERE Type_of_tank;
SELECT INSTR('Dutron','t') FROM water_tank;
SELECT SUBSTR('Dutron',1,3) FROM water_tank;
SELECT CONCAT(S_N,brand) FROM water_tank;



SELECT * FROM shoe_info;
ALTER TABLE shoe_info MODIFY size INT;
ALTER TABLE shoe_info ADD COLUMN Type varchar(50);
ALTER TABLE shoe_info RENAME COLUMN color TO colors;
UPDATE shoe_info SET brand='Nikee' WHERE shoe_id=1;
SELECT * FROM shoe_info WHERE colors='White';
SELECT * FROM shoe_info WHERE size-8 AND colors='White';
SELECT * FROM shoe_info WHERE size-8 OR colors='White';
SELECT *FROM shoe_info WHERE shoe_id IN(2,7,9);
SELECT *FROM shoe_info WHERE shoe_id NOT IN(8,10);
SELECT *FROM shoe_info WHERE shoe_id BETWEEN 1 AND 5;
SELECT COUNT(brand) FROM shoe_info;
SELECT SUM(size) AS total_size FROM shoe_info;
SELECT AVG(size) AS AVERAGE FROM shoe_info;
SELECT MIN(price) AS MIN_price FROM shoe_info;
SELECT MAX(price) AS MAX_price FROM shoe_info;
SELECT * FROM shoe_info ORDER BY price;
SELECT * FROM shoe_info ORDER BY price DESC;
SELECT DISTINCT(brand) FROM shoe_info;
SELECT LPAD('Puma',9,'s') FROM shoe_info WHERE shoe_id=3;
SELECT RPAD('Vans',7,'t') FROM shoe_info WHERE shoe_id=5;
UPDATE shoe_info SET brand='   Converse   ' WHERE shoe_id=7;
SELECT LTRIM(brand) FROM shoe_info WHERE shoe_id=7;
SELECT RTRIM(brand) FROM shoe_info WHERE shoe_id=7;
SELECT COUNT(price),price FROM shoe_info GROUP BY price;
SELECT COUNT(price),price FROM shoe_info GROUP BY price HAVING price>6000;
SELECT *FROM shoe_info WHERE brand LIKE 'A%';
SELECT *FROM shoe_info WHERE brand LIKE '%A';
SELECT *FROM shoe_info WHERE brand LIKE 'a%l';
SELECT UPPER(brand) FROM shoe_info WHERE shoe_id=3;
SELECT LOWER(brand) FROM shoe_info WHERE shoe_id=6;
SELECT UPPER(brand) FROM shoe_info;
SELECT INSTR('Adidas','d') FROM shoe_info;
SELECT SUBSTR('Vans',1,3) FROM shoe_info;
SELECT CONCAT(brand,colors) FROM shoe_info;


SELECT * FROM mobile_info;
ALTER TABLE mobile_info MODIFY display_size INT;
ALTER TABLE mobile_info ADD COLUMN Type varchar(50);
ALTER TABLE mobile_info RENAME COLUMN model TO models;
UPDATE mobile_info SET brand='Samsungg' WHERE id=2;
SELECT * FROM mobile_info WHERE ram='6GB';
SELECT * FROM mobile_info WHERE ram='6GB' AND storage='256GB';
SELECT * FROM mobile_info WHERE ram='6GB' OR storage='256GB';
SELECT *FROM mobile_info WHERE id IN(2,7,9);
SELECT *FROM mobile_info WHERE id NOT IN(8,10);
SELECT *FROM mobile_info WHERE id BETWEEN 1 AND 5;
SELECT COUNT(price) FROM mobile_info;
SELECT SUM(price) AS total_weight FROM mobile_info;
SELECT AVG(price) AS AVERAGE FROM mobile_info;
SELECT MIN(price) AS MIN_price FROM mobile_info;
SELECT MAX(price) AS MAX_price FROM mobile_info;
SELECT * FROM mobile_info ORDER BY price;
SELECT * FROM mobile_info ORDER BY price DESC;
SELECT DISTINCT(brand) FROM mobile_info;
SELECT LPAD('OnePlus',9,'s') FROM mobile_info WHERE id=3;
SELECT RPAD('Xiaomi',7,'t') FROM mobile_info WHERE id=5;
UPDATE mobile_info SET brand='   Samsung   ' WHERE id=7;
SELECT LTRIM(brand) FROM mobile_info WHERE id=7;
SELECT RTRIM(brand) FROM mobile_info WHERE id=7;
SELECT COUNT(price),price FROM mobile_info GROUP BY price;
SELECT COUNT(price),price FROM mobile_info GROUP BY price HAVING price>150;
SELECT *FROM mobile_info WHERE brand LIKE 'a%';
SELECT *FROM mobile_info WHERE brand LIKE '%l';
SELECT *FROM mobile_info WHERE brand LIKE 'a%l';
SELECT UPPER(brand) FROM mobile_info WHERE id=3;
SELECT LOWER(brand) FROM mobile_info WHERE id=6;
SELECT UPPER(brand) FROM mobile_info;
SELECT INSTR('Apple','p') FROM mobile_info;
SELECT SUBSTR('OnePlus',1,3) FROM mobile_info;
SELECT CONCAT(id,brand) FROM mobile_info;

SELECT * FROM laptop_info;
ALTER TABLE laptop_info MODIFY price INT;
ALTER TABLE laptop_info ADD COLUMN Type varchar(50);
ALTER TABLE laptop_info RENAME COLUMN Type TO laptop_info;
UPDATE laptop_info SET brand='Sup' WHERE S_N =2;
SELECT * FROM laptop_info WHERE ram='8GB';
SELECT * FROM laptop_info WHERE ram='8GB' AND display_size=14;
SELECT * FROM laptop_info WHERE ram='8GB' OR display_size=14;
SELECT *FROM laptop_info WHERE S_N IN(2,7,9);
SELECT *FROM laptop_info WHERE S_N NOT IN(8,10);
SELECT *FROM laptop_info WHERE S_N BETWEEN 1 AND 5;
SELECT COUNT(brand) FROM laptop_info;
SELECT SUM(price) AS total_weight FROM laptop_info;
SELECT AVG(price) AS AVERAGE FROM laptop_info;
SELECT MIN(price) AS MIN_price FROM laptop_info;
SELECT MAX(price) AS MAX_priceT FROM laptop_info;
SELECT * FROM laptop_info ORDER BY price;
SELECT * FROM laptop_info ORDER BY price DESC;
SELECT DISTINCT(brand) FROM laptop_info;
SELECT LPAD('HP',9,'s') FROM laptop_info WHERE S_N=3;
SELECT RPAD('ASUS',7,'t') FROM laptop_info WHERE S_N=5;
UPDATE laptop_info SET brand='   kisan   ' WHERE S_N=7;
SELECT LTRIM(brand) FROM laptop_info WHERE S_N=7;
SELECT RTRIM(brand) FROM laptop_info WHERE S_N=7;
SELECT COUNT(price),price FROM laptop_info GROUP BY price;
SELECT COUNT(price),price FROM laptop_info GROUP BY price HAVING price>5000;
SELECT *FROM laptop_info WHERE brand LIKE 'a%';
SELECT *FROM laptop_info WHERE brand LIKE '%l';
SELECT *FROM laptop_info WHERE brand LIKE 'a%l';
SELECT UPPER(brand) FROM laptop_info WHERE S_N=3;
SELECT LOWER(brand) FROM laptop_info WHERE S_N=6;
SELECT UPPER(brand) FROM laptop_info;
SELECT INSTR('Lenovo','t') FROM laptop_info;
SELECT SUBSTR('Dell',1,3) FROM laptop_info;
SELECT CONCAT(S_N,brand) FROM laptop_info;

SELECT *FROM bicycle_info;
ALTER TABLE bicycle_info MODIFY price INT;
ALTER TABLE bicycle_info ADD COLUMN Type varchar(50);
ALTER TABLE bicycle_info RENAME COLUMN model TO models;
UPDATE bicycle_info SET brand='Hello' WHERE id=2;
SELECT * FROM bicycle_info WHERE Type='Road';
SELECT * FROM bicycle_info WHERE Type='Road' AND Price=2500;
SELECT * FROM bicycle_info WHERE Type='Road' OR Price=2500;
SELECT *FROM bicycle_info WHERE id IN(2,7,9);
SELECT *FROM bicycle_info WHERE id NOT IN(8,10);
SELECT *FROM bicycle_info WHERE id BETWEEN 1 AND 5;
SELECT COUNT(price) FROM bicycle_info;
SELECT SUM(price) AS total_weight FROM bicycle_info;
SELECT AVG(price) AS AVERAGE FROM bicycle_info;
SELECT MIN(price) AS MIN_price FROM bicycle_info;
SELECT MAX(price) AS MAX_price FROM bicycle_info;
SELECT * FROM bicycle_info ORDER BY price;
SELECT * FROM bicycle_info ORDER BY price DESC;
SELECT DISTINCT(Brand) FROM bicycle_info;
SELECT LPAD('Specialized',12,'s') FROM bicycle_info WHERE id=3;
SELECT RPAD('Santa Cruz',15,'t') FROM bicycle_info WHERE id=5;
UPDATE bicycle_info SET Brand='   BMC   ' WHERE id=7;
SELECT LTRIM(Brand) FROM bicycle_info WHERE id=7;
SELECT RTRIM(Brand) FROM bicycle_info WHERE id=7;
SELECT COUNT(price),price FROM bicycle_info GROUP BY price;
SELECT COUNT(price),price FROM bicycle_info GROUP BY price HAVING price>150;
SELECT *FROM bicycle_info WHERE Brand LIKE 'a%';
SELECT *FROM bicycle_info WHERE Brand LIKE '%l';
SELECT *FROM bicycle_info WHERE Brand LIKE 'a%l';
SELECT UPPER(Brand) FROM bicycle_info WHERE id=3;
SELECT LOWER(Brand) FROM bicycle_info WHERE id=6;
SELECT UPPER(Brand) FROM bicycle_info;
SELECT INSTR('Scott','c') FROM bicycle_info;
SELECT SUBSTR('Canyon',1,3) FROM bicycle_info;
SELECT CONCAT(id,Brand) FROM bicycle_info;

SELECT * FROM watch_info;
ALTER TABLE watch_info MODIFY price INT;
ALTER TABLE watch_info ADD COLUMN Type varchar(50);
UPDATE watch_info SET brand='Samsungg' WHERE id=2;
SELECT * FROM watch_info WHERE dial_color='Black';
SELECT * FROM watch_info WHERE dial_color='Black' AND brand='Rolex';
SELECT * FROM watch_info WHERE dial_color='Black' OR brand='Rolex';
SELECT *FROM watch_info WHERE id IN(2,7,9);
SELECT *FROM watch_info WHERE id NOT IN(8,10);
SELECT *FROM watch_info WHERE id BETWEEN 1 AND 5;
SELECT COUNT(price) FROM watch_info;
SELECT SUM(price) AS total_weight FROM watch_info;
SELECT AVG(price) AS AVERAGE FROM watch_info;
SELECT MIN(price) AS MIN_price FROM watch_info;
SELECT MAX(price) AS MAX_price FROM watch_info;
SELECT * FROM watch_info ORDER BY price;
SELECT * FROM watch_info ORDER BY price DESC;
SELECT DISTINCT(brand) FROM watch_info;
SELECT LPAD('Fossil Grant',9,'s') FROM watch_info WHERE id=3;
SELECT RPAD('Fossil Grant',7,'t') FROM watch_info WHERE id=5;
UPDATE watch_info SET brand='   Samsung   ' WHERE id=7;
SELECT LTRIM(brand) FROM watch_info WHERE id=7;
SELECT RTRIM(brand) FROM watch_info WHERE id=7;
SELECT COUNT(price),price FROM watch_info GROUP BY price;
SELECT COUNT(price),price FROM watch_info GROUP BY price HAVING price>150;
SELECT *FROM watch_info WHERE brand LIKE 'a%';
SELECT *FROM watch_info WHERE brand LIKE '%l';
SELECT *FROM watch_info WHERE brand LIKE 'a%l';
SELECT UPPER(brand) FROM watch_info WHERE id=3;
SELECT LOWER(brand) FROM watch_info WHERE id=6;
SELECT UPPER(brand) FROM watch_info;
SELECT INSTR('Rolex Submariner','p') FROM watch_info;
SELECT SUBSTR('Rolex Submariner',1,3) FROM watch_info;
SELECT CONCAT(id,brand) FROM watch_info;


SELECT *FROM refrigerator_info;
SELECT * FROM refrigerator_info;
ALTER TABLE refrigerator_info MODIFY price INT;
UPDATE refrigerator_info SET brand='Samsungg' WHERE id=2;
SELECT * FROM refrigerator_info WHERE color='Black';
SELECT * FROM refrigerator_info WHERE color='Black' AND brand='LG';
SELECT * FROM refrigerator_info WHERE color='Black' OR brand='LG';
SELECT *FROM refrigerator_info WHERE id IN(2,7,9);
SELECT *FROM refrigerator_info WHERE id NOT IN(8,10);
SELECT *FROM refrigerator_info WHERE id BETWEEN 1 AND 5;
SELECT COUNT(price) FROM refrigerator_info;
SELECT SUM(price) AS total_weight FROM refrigerator_info;
SELECT AVG(price) AS AVERAGE FROM refrigerator_info;
SELECT MIN(price) AS MIN_price FROM refrigerator_info;
SELECT MAX(price) AS MAX_price FROM refrigerator_info;
SELECT * FROM refrigerator_info ORDER BY price;
SELECT * FROM refrigerator_info ORDER BY price DESC;
SELECT DISTINCT(brand) FROM refrigerator_info;
SELECT LPAD('Whirlpool',9,'s') FROM refrigerator_info WHERE id=3;
SELECT RPAD('KitchenAid',7,'t') FROM refrigerator_info WHERE id=5;
UPDATE refrigerator_info SET brand='   Frigidaire   ' WHERE id=7;
SELECT LTRIM(brand) FROM refrigerator_info WHERE id=7;
SELECT RTRIM(brand) FROM refrigerator_info WHERE id=7;
SELECT COUNT(price),price FROM refrigerator_info GROUP BY price;
SELECT COUNT(price),price FROM refrigerator_info GROUP BY price HAVING price>150;
SELECT *FROM refrigerator_info WHERE brand LIKE 'a%';
SELECT *FROM refrigerator_info WHERE brand LIKE '%l';
SELECT *FROM refrigerator_info WHERE brand LIKE 'a%l';
SELECT UPPER(brand) FROM refrigerator_info WHERE id=3;
SELECT LOWER(brand) FROM refrigerator_info WHERE id=6;
SELECT UPPER(brand) FROM refrigerator_info;
SELECT INSTR('Frigidaire','i') FROM refrigerator_info;
SELECT SUBSTR('Frigidaire',1,3) FROM refrigerator_info;
SELECT CONCAT(id,brand) FROM refrigerator_info;

SELECT * FROM backpack;
ALTER TABLE backpack MODIFY price INT;
UPDATE backpack SET brand='Samsungg' WHERE id=12;
SELECT * FROM backpack WHERE color='Black';
SELECT * FROM backpack WHERE color='Black' AND brand='Thule';
SELECT * FROM backpack WHERE color='Black' OR brand='Thule';
SELECT *FROM backpack WHERE id IN(12,17,19);
SELECT *FROM backpack WHERE id NOT IN(18,10);
SELECT *FROM backpack WHERE id BETWEEN 11 AND 15;
SELECT COUNT(price) FROM backpack;
SELECT SUM(price) AS total_weight FROM backpack;
SELECT AVG(price) AS AVERAGE FROM backpack;
SELECT MIN(price) AS MIN_price FROM backpack;
SELECT MAX(price) AS MAX_price FROM backpack;
SELECT * FROM backpack ORDER BY price;
SELECT * FROM backpack ORDER BY price DESC;
SELECT DISTINCT(brand) FROM backpack;
SELECT LPAD('Under Armour',9,'s') FROM backpack WHERE id=13;
SELECT RPAD('Kelty',7,'t') FROM backpack WHERE id=15;
UPDATE backpack SET brand='   Mountainsmith   ' WHERE id=17;
SELECT LTRIM(brand) FROM backpack WHERE id=7;
SELECT RTRIM(brand) FROM backpack WHERE id=7;
SELECT COUNT(price),price FROM backpack GROUP BY price;
SELECT COUNT(price),price FROM backpack GROUP BY price HAVING price>150;
SELECT *FROM backpack WHERE brand LIKE 'a%';
SELECT *FROM backpack WHERE brand LIKE '%l';
SELECT *FROM backpack WHERE brand LIKE 'a%l';
SELECT UPPER(brand) FROM backpack WHERE id=13;
SELECT LOWER(brand) FROM backpack WHERE id=16;
SELECT UPPER(brand) FROM backpack;
SELECT INSTR('Mountainsmith','i') FROM backpack;
SELECT SUBSTR('Mountainsmith',1,3) FROM backpack;
SELECT CONCAT(id,brand) FROM backpack;

SELECT * FROM waterbottle_info;
ALTER TABLE waterbottle_info MODIFY price INT;
UPDATE waterbottle_info SET brand='Samsungg' WHERE id=2;
SELECT * FROM waterbottle_info WHERE color='Black';
SELECT * FROM waterbottle_info WHERE color='Black' AND brand='Hydro Flask';
SELECT * FROM waterbottle_info WHERE color='Black' OR brand='Hydro Flask';
SELECT *FROM waterbottle_info WHERE id IN(2,7,9);
SELECT *FROM waterbottle_info WHERE id NOT IN(8,10);
SELECT *FROM waterbottle_info WHERE id BETWEEN 1 AND 5;
SELECT COUNT(price) FROM waterbottle_info;
SELECT SUM(price) AS total_weight FROM waterbottle_info;
SELECT AVG(price) AS AVERAGE FROM waterbottle_info;
SELECT MIN(price) AS MIN_price FROM waterbottle_info;
SELECT MAX(price) AS MAX_price FROM waterbottle_info;
SELECT * FROM waterbottle_info ORDER BY price;
SELECT * FROM waterbottle_info ORDER BY price DESC;
SELECT DISTINCT(brand) FROM waterbottle_info;
SELECT LPAD('Nalgene',9,'s') FROM waterbottle_info WHERE id=3;
SELECT RPAD('Klean Kanteen',7,'t') FROM waterbottle_info WHERE id=5;
UPDATE waterbottle_info SET brand='   Contigo   ' WHERE id=7;
SELECT LTRIM(brand) FROM waterbottle_info WHERE id=7;
SELECT RTRIM(brand) FROM waterbottle_info WHERE id=7;
SELECT COUNT(price),price FROM waterbottle_info GROUP BY price;
SELECT COUNT(price),price FROM waterbottle_info GROUP BY price HAVING price>150;
SELECT *FROM waterbottle_info WHERE brand LIKE 'a%';
SELECT *FROM waterbottle_info WHERE brand LIKE '%l';
SELECT *FROM waterbottle_info WHERE brand LIKE 'a%l';
SELECT UPPER(brand) FROM waterbottle_info WHERE id=3;
SELECT LOWER(brand) FROM waterbottle_info WHERE id=6;
SELECT UPPER(brand) FROM waterbottle_info;
SELECT INSTR('Contigo','i') FROM waterbottle_info;
SELECT SUBSTR('Contigo',1,3) FROM waterbottle_info;
SELECT CONCAT(id,brand) FROM waterbottle_info;

SELECT * FROM remote_info;
ALTER TABLE remote_info MODIFY price INT;
UPDATE remote_info SET brand='Samsungg' WHERE id=2;
SELECT * FROM remote_info WHERE color='Black';
SELECT * FROM remote_info WHERE color='Black' AND brand='Samsung';
SELECT * FROM remote_info WHERE color='Black' OR brand='Samsung';
SELECT *FROM remote_info WHERE id IN(2,7,9);
SELECT *FROM remote_info WHERE id NOT IN(8,10);
SELECT *FROM remote_info WHERE id BETWEEN 1 AND 5;
SELECT COUNT(price) FROM remote_info;
SELECT SUM(price) AS total_weight FROM remote_info;
SELECT AVG(price) AS AVERAGE FROM remote_info;
SELECT MIN(price) AS MIN_price FROM remote_info;
SELECT MAX(price) AS MAX_price FROM remote_info;
SELECT * FROM remote_info ORDER BY price;
SELECT * FROM remote_info ORDER BY price DESC;
SELECT DISTINCT(brand) FROM remote_info;
SELECT LPAD('Sony',9,'s') FROM remote_info WHERE id=3;
SELECT RPAD('Apple',7,'t') FROM remote_info WHERE id=5;
UPDATE remote_info SET brand='   Contigo   ' WHERE id=7;
SELECT LTRIM(brand) FROM remote_info WHERE id=7;
SELECT RTRIM(brand) FROM remote_info WHERE id=7;
SELECT COUNT(price),price FROM remote_info GROUP BY price;
SELECT COUNT(price),price FROM remote_info GROUP BY price HAVING price>150;
SELECT *FROM remote_info WHERE brand LIKE 'a%';
SELECT *FROM remote_info WHERE brand LIKE '%l';
SELECT *FROM remote_info WHERE brand LIKE 'a%l';
SELECT UPPER(brand) FROM remote_info WHERE id=3;
SELECT LOWER(brand) FROM remote_info WHERE id=6;
SELECT UPPER(brand) FROM remote_info;
SELECT INSTR('Apple','i') FROM remote_info;
SELECT SUBSTR('Apple',1,3) FROM remote_info;
SELECT CONCAT(id,brand) FROM remote_info;



    






