CREATE DATABASE June_07;
USE DATABASE June_07;
Use June_07;
create table Dog(S_N int,Name varchar(50),Species varchar(30),Age double,Gender varchar(30),Height double,Weight double,color varchar(40),Life_span int,birthday varchar(40));
desc June_07;
desc Dog;
desc table Dog;
create table States_in_India(S_N int,Name varchar(30),Area bigint,Capital_city varchar(30),Tourist_places varchar(50),Chief_Minister varchar(40),Finance_Minister varchar(40),Population bigint,No_of_voters bigint,No_of_airports int);
desc States_in_India;
desc States_in_India;
desc Universe
create table Famous_movie_songs(S_N int,Name_of_the_song varchar(30),Movie_name varchar(40),Music_director varchar(30),Male_singer_name varchar(30),Female_singer_name varchar(40),Relesased_year int,No_of_youtube_views bigint,No_of_likes bigint,Original_language varchar(40));

desc Famous_movie_songs
create table Karnataka_elections(Name_of_constituency varchar(40),Candidate_name varchar(30),Age int,Gender varchar(30),No_of_votes_he_got bigint,Total_no_of_voters bigint,No_of_times_won int,No_of_male_voters bigint,No_of_female bigint,Party_name varchar(40));
desc Karnataka_elections
create table Ipl_teams(S_N int,Captain_name varchar(40),First_order_batsmen varchar(30),Year_entered int,Sponsor_name varchar(30),No_of_cups_won int,year_won bigint,color_of_jersey varchar(30),No_of_foreign_players int,captain_during_win varchar(30));

desc Ipl_teams;
CREATE TABLE Netflix_films(S_N int,Name_of_film varchar(40),Duration int,Female_lead_name varchar(30),Male_lead_name varchar(30),No_Of_songs int,Year_released bigint,Film_director varchar(30),film_producer varchar(40),Music_director varchar(30));
desc  Netflix_films;
create table Apps_info(S_N int,Name_of_app varchar(30),Vendor varchar(40),Year_released bigint,purpose varchar(50),No_of_users bigint,Bandwidth double,Name_of_creators varchar(30),Version varchar(30),Reviews_in_playstore double);
desc Apps_info;
create table satellites_info(S_N int,Name_Of_Satellite varchar(30),Purpose varchar(40),Space_center_name varchar(40),destination varchar(30),Weight double,Speed bigint,Date_of_launch varchar(40),diameter bigint,lifespan bigint);
desc satellites_info;
create table Padma_awards_2023(S_N int,Name_of_the_person varchar(40),Award_name varchar(30),Field varchar(40),Gender varchar(40),Age int,State varchar(30),Date_of_receiving_award varchar(30),place_of_presenting_award varchar(30),Time_of_receiving_award double);

desc Padma_awards_2023;
